export const stations = [
  // Add or edit Korean FM stations here.
  // `streamType` decides how the app finds the real audio stream.
  {
    id: 'kbs-cool-fm',
    name: 'KBS Cool FM',
    frequency: '89.1',
    streamType: 'json-api',
    apiUrl: '/api/kbs?channelCode=25',
    streamUrl: '',
    isPlayable: true,
  },
  {
    id: 'mbc-fm4u',
    name: 'MBC FM4U',
    frequency: '91.9',
    streamType: 'json-api',
    apiUrl: '/api/mbc?agent=webapp&channel=mfm',
    streamUrl: '',
    isPlayable: true,
  },
  {
    id: 'kbs-classic-fm',
    name: 'KBS Classic FM',
    frequency: '93.1',
    streamType: 'json-api',
    apiUrl: '/api/kbs?channelCode=24',
    streamUrl: '',
    isPlayable: true,
  },
  {
    id: 'ytn-radio',
    name: 'YTN Radio',
    frequency: '94.5',
    streamType: 'direct',
    apiUrl: '',
    streamUrl: 'https://radiolive.ytn.co.kr/radio/_definst_/20211118_fmlive/playlist.m3u8',
    isPlayable: true,
  },
  {
    id: 'tbs-fm',
    name: 'TBS FM',
    frequency: '95.1',
    streamType: 'direct',
    apiUrl: '',
    streamUrl: 'https://cdnfm.tbs.seoul.kr/tbs/_definst_/tbs_fm_web_360.smil/playlist.m3u8',
    isPlayable: true,
  },
  {
    id: 'mbc-standard-fm',
    name: 'MBC Standard FM',
    frequency: '95.9',
    streamType: 'json-api',
    apiUrl: '/api/mbc?agent=webapp&channel=sfm',
    streamUrl: '',
    isPlayable: true,
  },
  {
    id: 'gugak-fm',
    name: 'Gugak FM',
    frequency: '99.1',
    streamType: 'direct',
    apiUrl: '',
    streamUrl: 'https://mgugaklive.nowcdn.co.kr/gugakradio/gugakradio.stream/playlist.m3u8',
    isPlayable: true,
  },
  {
    id: 'tbs-efm',
    name: 'TBS eFM',
    frequency: '101.3',
    streamType: 'direct',
    apiUrl: '',
    streamUrl: 'https://cdnefm.tbs.seoul.kr/tbs/_definst_/tbs_efm_web_360.smil/playlist.m3u8',
    isPlayable: true,
  },
  {
    id: 'sbs-love-fm',
    name: 'SBS Love FM',
    frequency: '103.5',
    streamType: 'plain-text-api',
    apiUrl: 'https://apis.sbs.co.kr/play-api/1.0/livestream/lovepc/lovefm?protocol=hls&ssl=Y',
    streamUrl: '',
    isPlayable: true,
  },
  {
    id: 'ebs-fm',
    name: 'EBS FM',
    frequency: '104.5',
    streamType: 'direct',
    apiUrl: '',
    streamUrl: 'https://ebsonair.ebs.co.kr/fmradiofamilypc/familypc1m/playlist.m3u8',
    isPlayable: true,
  },
  {
    id: 'febc',
    name: 'FEBC',
    frequency: '106.9',
    streamType: 'direct',
    apiUrl: '',
    streamUrl: 'https://mlive3.febc.net/live5/seoulfm/playlist.m3u8',
    isPlayable: true,
  },
  {
    id: 'sbs-power-fm',
    name: 'SBS Power FM',
    frequency: '107.7',
    streamType: 'plain-text-api',
    apiUrl: 'https://apis.sbs.co.kr/play-api/1.0/livestream/powerpc/powerfm?protocol=hls&ssl=Y',
    streamUrl: '',
    isPlayable: true,
  },
]
